### PR TITLE
- Fix sbr_knit_results()

### LINKED ISSUE #31: Fix sbr_knit_results()

### PR DESCRIPTION
**Pull request by joethorley**
Fixes #31

### CODE REVIEW

File: R/subreport-package.R [hunk 1]
```diff
@@ -1,2 +1,10 @@
 #' @keywords internal
 "_PACKAGE"
+
+## usethis namespace: start
+#' @importFrom term as_term
```
Comment (aylapear) [inline R/subreport-package.R]: Add a comment to why this is needed

**Review by aylapear — CHANGES_REQUESTED** [review]
